apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: muuhc21cl-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: muuhc21cl-go 
  name: muuhc21cl-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: muuhc21cl-go 
